"""imag_id nullable shop table

Revision ID: da08baf3973d
Revises: 53b817550ac8
Create Date: 2026-02-28 07:43:29.091176

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da08baf3973d"
down_revision: Union[str, Sequence[str], None] = "53b817550ac8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("shops", "image_id", existing_type=sa.BIGINT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("shops", "image_id", existing_type=sa.BIGINT(), nullable=False)
    # ### end Alembic commands ###
